steps:
  - command: echo 'Tests'
    label: ':hammer: Tests'
  - wait
  - trigger: dependent-pipeline-example-deploy
    label: ":rocket: Trigger deploy"
    branches: "main"
    async: true
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"
