name: "Dependent Pipeline Example (Deploy)"
description: "An example pipeline that is triggered by another pipeline to perform a deployment."
emoji: ":rocket:"
steps:
  - label: ":pipeline:"
    command: "buildkite-agent pipeline upload .buildkite/pipeline.deploy.yml"
